title: Haozhuo Zhang's Homepage
page-top-title: Haozhuo Zhang
top-section-bg-text: Scarred Souls Shine like Stars
home-subtitle: Yourname&ensp;|&ensp;Hugo
copyright-text: '&copy; Haozhuo Zhang 2026. All Rights Reserved.'
